use_frameworks!

platform :ios, '9.0'

target 'xPageViewController_Example' do
  pod 'xPageViewController', :path => '../'

  target 'xPageViewController_Tests' do
    inherit! :search_paths

    
  end
end
